config/routes.rb
Asamblea::Application.routes.draw do
  resources :usuarios

   root :to => 'usuarios#index'

end

app/models/condicion.rb
class Condicion < ActiveRecord::Base
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :ci, :condicion_id, :credencial, :distrito_id, :nombre, :region_id
  validates_presence_of :ci, :condicion_id, :credencial, :distrito_id, :nombre, :region_id
  validates_uniqueness_of :ci, :credencial
  belongs_to :region
  belongs_to :distrito
  belongs_to :condicion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/condicions_controller.rb
class CondicionsController < ApplicationController
	def condicion
		#{self.condicion}
	end
end

app/controllers/distritos_controller.rb
class DistritosController < ApplicationController
	def distrito
		#{self.distito}
	end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
	def region
		#{self.region}
	end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asamblea Nacional Scout del Centenario</title>
  <%= stylesheet_link_tag "application", :media => 'all' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombres y Apellidos" %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label "Cédula de Identidad" %><br />
    <%= f.text_field :ci %>
  </div>
  <div class="field">
    <%= f.label "Número de Credencial" %><br />
    <%= f.text_field :credencial %>
  </div>
    <div class="field">
    <%= f.label "Región" %><br />
    <%= f.collection_select(:region_id, Region.all, :id, :region, :prompt => true)%>
  </div>
  <div class="field">
    <%= f.label "Distrito" %><br />
    <%= f.collection_select(:distrito_id, Distrito.all, :id, :distrito, :prompt => true)%>
  </div>
  <div class="field">
    <%= f.label "Condición" %><br />
    <%= f.collection_select(:condicion_id, Condicion.all, :id, :condicion, :prompt => true)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editar datos del participante</h1>

<%= render 'form' %>

<%= link_to 'Mostrar datos', @usuario %> |
<%= link_to 'Menú principal', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Participantes a la Asamblea Nacional Scout del Centenario</h1>

<table>
  <tr>
    <th>Nombres y Apellidos</th>
    <th>Cédula de Identidad</th>
    <th>Credencial</th>
    <th>Región</th>
    <th>Distrito</th>
    <th>Condición</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.nombre %></td>
    <td><%= usuario.ci %></td>
    <td><%= usuario.credencial %></td>
    <td><%= usuario.region.region %></td>
    <td><%= usuario.distrito.distrito %></td>
    <td><%= usuario.condicion.condicion %></td>
    <td><%= link_to 'Acreditar', usuario %></td>
    <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Eliminar', usuario, method: :delete, data: { confirm: 'Favor confirmar' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Registro de nuevo participante', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Registro de nuevo participante</h1>

<%= render 'form' %>

<%= link_to 'Menú principal', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @usuario.nombre %>
</p>

<p>
  <b>Cédula de identidad:</b>
  <%= @usuario.ci %>
</p>

<p>
  <b>Número de Credencial:</b>
  <%= @usuario.credencial %>
</p>

<p>
  <b>Región:</b>
  <%= @usuario.region.region %>
</p>

<p>
  <b>Distrito:</b>
  <%= @usuario.distrito.distrito %>
</p>

<p>
  <b>Condición:</b>
  <%= @usuario.condicion.condicion %>
</p>

<p id="pdf_link">
<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Menú principal', usuarios_path %> |
<%= link_to "Imprimir acreditación", usuario_path(@usuario, :format => "pdf") %></p>